# Generated by Django 3.1.5 on 2021-01-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
