# Generated by Django 3.1.5 on 2021-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210130_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideos',
            name='video',
        ),
        migrations.AddField(
            model_name='uploadvideos',
            name='songs',
            field=models.FileField(default=False, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
